import React from 'react';
import { motion } from 'framer-motion';
import { Cpu, Globe, Zap } from 'lucide-react';

export const About: React.FC = () => {
  const features = [
    { icon: <Cpu className="w-6 h-6" />, title: 'Neural Design', desc: 'Generated by AI, refined by human hands.' },
    { icon: <Globe className="w-6 h-6" />, title: 'Eco-Synth Materials', desc: '100% recycled synthetic compounds.' },
    { icon: <Zap className="w-6 h-6" />, title: 'Quantum Charged', desc: 'Embedded with low-energy luminescence.' },
  ];

  return (
    <section id="about" className="py-24 relative bg-nebula-900 overflow-hidden">
      <div className="container mx-auto px-6">
        <div className="flex flex-col lg:flex-row items-center gap-16">
          {/* Image Area */}
          <motion.div 
            initial={{ opacity: 0, x: -50 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.8 }}
            className="lg:w-1/2 relative"
          >
            <div className="relative z-10 rounded-2xl overflow-hidden border border-white/10 shadow-2xl group">
              <div className="absolute inset-0 bg-gradient-to-t from-nebula-900 via-transparent to-transparent opacity-60" />
              <img 
                src="https://picsum.photos/seed/nebulaart/800/1000" 
                alt="Artisan working on futuristic tech" 
                className="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-700"
              />
            </div>
            {/* Decorative Backdrop */}
            <div className="absolute -inset-4 bg-gradient-to-r from-nebula-500 to-nebula-cyan rounded-2xl blur-xl opacity-30 -z-10" />
          </motion.div>

          {/* Content Area */}
          <motion.div 
            initial={{ opacity: 0, x: 50 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.8 }}
            className="lg:w-1/2"
          >
            <h2 className="text-4xl md:text-5xl font-bold mb-6 text-white">
              Bridging the Gap Between <span className="text-nebula-cyan">Digital</span> & <span className="text-nebula-500">Physical</span>
            </h2>
            <p className="text-gray-400 text-lg mb-8 leading-relaxed">
              NebulaCraft began as an experiment in 2042. Our mission is to bring the ephemeral beauty of cyberspace into the tactile world. Every object is a solidified memory of a digital dream, crafted with precision and imbued with the spirit of the new age.
            </p>

            <div className="grid gap-6">
              {features.map((f, i) => (
                <motion.div 
                  key={i}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: i * 0.1 }}
                  className="flex items-start gap-4 p-4 rounded-xl bg-white/5 border border-white/5 hover:border-nebula-cyan/30 transition-colors"
                >
                  <div className="p-3 rounded-lg bg-nebula-800 text-nebula-cyan">
                    {f.icon}
                  </div>
                  <div>
                    <h3 className="text-xl font-semibold text-white mb-1">{f.title}</h3>
                    <p className="text-sm text-gray-400">{f.desc}</p>
                  </div>
                </motion.div>
              ))}
            </div>
          </motion.div>
        </div>
      </div>
    </section>
  );
};
